"use client";
import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, BarChart3, Database, Lightbulb, LockKeyhole, Plus, Radio, Send, ShieldCheck, Sparkles, TrendingUp, Upload } from "lucide-react";

type Activity={name:string;platform:string;reach:number;engagement:number;bookings:number;effort:number;source:"Auto"|"Manuell"};
const initial:Activity[]=[{name:"Backflip #47 Reveal",platform:"Instagram",reach:18400,engagement:8.7,bookings:7,effort:3,source:"Auto"},{name:"Fear → First Flip",platform:"TikTok",reach:31200,engagement:12.4,bookings:4,effort:2,source:"Auto"},{name:"Founder Mission",platform:"YouTube Shorts",reach:8900,engagement:6.1,bookings:2,effort:4,source:"Manuell"}];
const platforms=[{name:"Instagram",core:true,status:"Connected"},{name:"TikTok",core:true,status:"Connected"},{name:"YouTube Shorts",core:true,status:"Connect"},{name:"X",core:true,status:"Connect"},{name:"LinkedIn",core:false,status:"Optional"},{name:"Bilibili",core:false,status:"Optional"}];
const score=(a:Activity)=>Math.round(a.engagement*3+a.bookings*5+Math.log10(Math.max(a.reach,1))*8-a.effort*4);

export default function Admin(){
 const [login,setLogin]=useState(false),[tab,setTab]=useState("overview"),[activities,setActivities]=useState(initial),[idea,setIdea]=useState("");
 const [ideas,setIdeas]=useState(["Hamburg Stadtteil-Battle","Journalist lernt Backflip in 60 Minuten"]);
 const winner=useMemo(()=>[...activities].sort((a,b)=>score(b)-score(a))[0],[activities]);
 const submitIdea=(e:FormEvent)=>{e.preventDefault();if(idea.trim()){setIdeas([idea.trim(),...ideas]);setIdea("")}};
 const addActivity=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setActivities([{name:String(d.get("name")),platform:String(d.get("platform")),reach:Number(d.get("reach")),engagement:Number(d.get("engagement")),bookings:Number(d.get("bookings")),effort:Number(d.get("effort")),source:"Manuell"},...activities]);e.currentTarget.reset()};
 if(!login)return <main className="loginScreen"><a href="/" className="backLink"><ArrowLeft size={15}/> Campaign</a><section className="loginCard"><LockKeyhole/><p className="adminEyebrow">SALTO CAMPAIGN OS / ADMIN</p><h1>INTELLIGENCE<br/>BRAUCHT DATEN.</h1><p>Geschützter Bereich für Ideen, Performance und Entscheidungen. Der Preview-Login speichert keine echten Zugangsdaten.</p><label>E-MAIL<input defaultValue="jeaaares@preview.local" type="email"/></label><button onClick={()=>setLogin(true)}>PREVIEW LOGIN <ArrowUpRight size={17}/></button><small><ShieldCheck size={13}/> Produktion: Magic Link + geschützte Server-Routen</small></section></main>;
 const nav=[["overview","Overview",BarChart3],["ideas","Ideen",Lightbulb],["activities","Aktivitäten",Radio],["platforms","Plattformen",Upload],["architecture","Architektur",Database]] as const;
 return <main className="adminShell"><aside className="adminSide"><a href="/">JEAAARES®</a><nav>{nav.map(([id,label,Icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon size={17}/>{label}</button>)}</nav><div className="adminUser"><span>JL</span><div><strong>Jean-Luc</strong><small>ADMIN</small></div></div></aside><section className="adminMain"><header className="adminHeader"><div><p className="adminEyebrow">CHAPTER 01 / INTELLIGENCE</p><h1>{tab}</h1></div><span className="sync"><i/> 2 SOURCES LIVE</span></header>
 {tab==="overview"&&<><section className="biGrid"><article><span>BACKFLIPS</span><strong>47</strong><small>+12 diese Woche</small></article><article><span>REACH</span><strong>58.5K</strong><small>↑ 34% vs. Baseline</small></article><article><span>BOOKINGS</span><strong>13</strong><small>22% aus Content</small></article><article><span>MOMENTUM</span><strong>78</strong><small>/ 100 · STRONG</small></article></section><section className="intelPanel"><div><Sparkles/><p className="adminEyebrow">NÄCHSTE ENTSCHEIDUNG</p><h2>SKALIERE „{winner.name}“ MIT HÖHEREM EINSATZ.</h2><p>Stärkster Mechanismus bei gutem Verhältnis aus Reaktion, Buchungen und Aufwand. Nächster Test: gleiche Dramaturgie mit einer bekannten Hamburger Person.</p></div><div><TrendingUp/><strong>{score(winner)}</strong><small>DECISION SCORE</small></div></section><DataTable activities={activities}/></>}
 {tab==="ideas"&&<section className="adminCard"><p className="adminEyebrow">IDEA INBOX</p><h2>IDEE REIN. QUEST RAUS.</h2><form className="ideaForm" onSubmit={submitIdea}><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Was möchtest du ausprobieren?"/><button><Plus size={16}/> IDEE SUBMITTEN</button></form><div className="ideaList">{ideas.map((x,i)=><article key={x}><span>0{i+1}</span><div><strong>{x}</strong><p>Wird nach Story-Fit, Proof, Distribution, Aufwand und Unlock-Beitrag bewertet.</p></div><button>SCORING <ArrowUpRight size={14}/></button></article>)}</div></section>}
 {tab==="activities"&&<section className="activityLayout"><form className="adminCard trackingForm" onSubmit={addActivity}><p className="adminEyebrow">MANUAL FALLBACK</p><h2>AKTIVITÄT TRACKEN</h2><label>Name<input name="name" required/></label><label>Plattform<select name="platform">{platforms.map(p=><option key={p.name}>{p.name}</option>)}</select></label><div className="formGrid"><label>Reach<input name="reach" type="number" required/></label><label>Engagement %<input name="engagement" type="number" step=".1" required/></label><label>Bookings<input name="bookings" type="number" required/></label><label>Aufwand 1–5<input name="effort" type="number" min="1" max="5" required/></label></div><button><Send size={16}/> SPEICHERN & AUSWERTEN</button></form><section><DataTable activities={activities}/></section></section>}
 {tab==="platforms"&&<section className="adminCard"><p className="adminEyebrow">DISTRIBUTION MATRIX</p><h2>CORE ÜBERALL. NICHT ALLES IDENTISCH.</h2><p className="lead">Ein Core Asset wird je Plattform adaptiert. LinkedIn und Bilibili bleiben optional, bis Zielgruppe oder Partner den Aufwand rechtfertigen.</p><div className="platformGrid">{platforms.map(p=><article key={p.name}><div><i className={p.status==="Connected"?"on":""}/><strong>{p.name}</strong><small>{p.core?"CORE":"OPTIONAL"}</small></div><p>{p.name==="Bilibili"?"China-Test mit lokaler Adaption, Untertiteln und Partner-Setup.":"Hook, Format, Caption und CTA plattformspezifisch ausspielen."}</p><footer><span>Analytics</span><button>{p.status}</button></footer></article>)}</div></section>}
 {tab==="architecture"&&<section className="architecture"><div className="archFlow">{[["01","INPUT","Ideen · Posts · Events"],["02","DATA","APIs · Manual · Bookings"],["03","INTELLIGENCE","Normalize · Score · Diagnose"],["04","STORY ENGINE","Beat · Quest · Unlock"],["05","OUTPUT","Dashboard · Tasks · Alerts"]].map(x=><article key={x[0]}><span>{x[0]}</span><div><strong>{x[1]}</strong><p>{x[2]}</p></div><ArrowUpRight size={16}/></article>)}</div><div className="adminCard stack"><p className="adminEyebrow">PRODUCTION STACK</p><h2>EMPFOHLENE ARCHITEKTUR</h2>{[["Frontend","Next.js · Campaign + Admin"],["Auth","Magic Link · Admin-Rollen"],["Database","Postgres · Events + Metrics"],["Jobs","Scheduled API Syncs"],["Intelligence","Rules first · AI second"],["Audit","Source · Time · Override"]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>}
 </section></main>
}
function DataTable({activities}:{activities:Activity[]}){return <section className="dataTable"><div className="tableTitle"><h2>PERFORMANCE</h2><span>SCORE</span></div>{activities.map(a=><div className="dataRow" key={a.name}><div><strong>{a.name}</strong><small>{a.platform} · {a.source}</small></div><span>{a.reach.toLocaleString("de-DE")}</span><span>{a.engagement}% ER</span><span>{a.bookings} Bookings</span><b>{score(a)}</b></div>)}</section>}
